# Generated by Django 2.2.15 on 2020-08-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(verbose_name='Data do Peddo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.Client', verbose_name='Client Relacionado')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
    ]
