# Generated by Django 2.2.15 on 2020-08-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=6, verbose_name='Status do Pedido'),
        ),
        migrations.AddField(
            model_name='request',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Valor do Pedido'),
        ),
    ]
